services:
  - type: web
    name: my-django-blog
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn lms_project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        value: "<your-secret-key>"
      - key: ALLOWED_HOSTS
        value: "my-django-blog.onrender.com"
    autoDeploy: true
    healthCheckPath: /
    disk: 512
